### ISSUE TITLE
Need a cool name

### ISSUE THREAD

**Issue by mcelearr** [mcelearr/JSskillstracker#1]
It might not end up as a wagon wheel if that becomes too difficult to implement so it might not be a good idea to make the name super specific to the wagon wheel design. Anyway, here's two for a starter:

Wag-On
Wheelify

**Comment by coudrew** [comment]
[catherine wheels](https://en.wikipedia.org/wiki/Catherine_wheel_%28firework%29) are pretty cool, everyone likes fireworks

**Comment by mcelearr** [comment]
So it sounds like this needs to be a priority if we're going to get a prototype actually up and running. What we can do when building the site is use a placeholder 'user' object. i.e. create an object called 'Joe Bloggs' to take the place of the user details that would be passed from the GitHub API. As long as the format is the same, it should be fine.

**Comment by mcelearr** [comment]
Crap names lol:
Wheelaborate
Wheelove2learn

**Comment by mcelearr** [comment]
Looks like we're going with JS Radar!

**Comment by coudrew** [comment]
should prolly close this then?

**Comment by mcelearr** [comment]
Only if you're happy with it ;)

**Comment by coudrew** [comment]
did a quick search, if there's anything else called 'JS Radar' it's off page one of google (and therefore not a real thing). closing.
