### ISSUE TITLE
Create server-side PHP/AJAX to pull from github api

### ISSUE THREAD

**Issue by coudrew** [mcelearr/JSskillstracker#11]
Authentication will work client-side, but should be server-side to hide client id/secret

**Comment by mcelearr** [comment]
Yeah I've heard that as well. Back form to put it on the client side. How confident are you that you'll be able to figure it out? Do you need any help?

**Comment by mcelearr** [comment]
Why PHP? Can't we use node.js/ ruby on rails?

**Comment by coudrew** [comment]
I could use some help, yeah. MSG'd you on our gitter

**Comment by coudrew** [comment]
current version of the server can fetch from github, but data does not necessarily persist between requests, and two users logged in at the same time could end up viewing the same data. going to close this issue and raise one for cookies to identify client machines.
