### ISSUE TITLE
Get people to provide skills content

### ISSUE THREAD

**Issue by mcelearr** [mcelearr/JSskillstracker#14]
- Show people the prototype front-end.
- Ask people to suggest their own content.

**Comment by mcelearr** [comment]
There's an extra step in here which is to add some info on contributing

**Comment by samhstn** [comment]
@mcelearr Do you want this to be done in the app in perhaps a form or on github?

**Comment by mcelearr** [comment]
@shouston3 I was planning on getting people to contribute via github because then it gives people practice of git workflow and contributing to projects. Do you think there will be lots of merging issues with people trying to edit index.html at the same time? There's a .md that I used to collect my initial thoughts, I could ask people to make changes in there or maybe a google doc or form would be better...hmmmmmn. I think the first thing to do is to fill out one or two subskills with content the way i imagine it. That will set the 'standard' for other content contributions and give people ideas for how to chip in.

**Comment by samhstn** [comment]
@mcelearr I think having pre-fac people editing the index page would mean that unless you lay out some good formatting rules, you wouldn't get pull requests conforming to the format you need.
I think for the time being, a google doc or github issues would be the easy and better option, then we can refactor that later when everything else is set up

**Comment by mcelearr** [comment]
I'm going to use google forms.

**Comment by mcelearr** [comment]
Google form created.
