### ISSUE TITLE
Decide on hosting

### ISSUE THREAD

**Issue by mcelearr** [mcelearr/JSskillstracker#16]
We need to do some research and come up with a shortlist of hosting options so we can compare the costs.

ssl is $20 a month, but we could have our_app_name.herokuapp.com for free.

Ssl certificates from Fatcow were $40 a year, from AWS it's $600 a month but I have suspicion there's a much cheaper option. Also the paid for ssl with heroku is from client browser to the app, there may be a free option for the app to external server.

**Comment by coudrew** [comment]
ok, so hosting with heroku is free, and we can use cloudflare universal ssl for free. there may be some gotchas, but working around stuff can be fun.

**Comment by coudrew** [comment]
one thing we should definitely keep in mind for this: testing the application for users who are not logged in can be done on a locahost, but anything to do with OAuth will require a server and domain that our github application is pointing at. the ability for multiple (apporoved) users to ssh in to the server for testing  would be nice.

**Comment by samhstn** [comment]
@coudrew You should be able to test for users who are logged in with OAuth on localhost

**Comment by coudrew** [comment]
@shouston3 really?! Do you know how to set it up? It's kind of a huge hassle right now to test.

**Comment by samhstn** [comment]
@coudrew I can show you the next time your in fac, actually @mcelearr @coudrew I think it would be fun to meet up and chat about the current state of the application, when would you guys be free to meet?

**Comment by samhstn** [comment]
@mcelearr @coudrew Also, I just showed some people at fac the current app, everyone is amazed by what you guys have done so far. Its all really impressive, keep it up!

**Comment by coudrew** [comment]
@shouston3 nice! i'm busy this weekend with a meetup on Saturday and Sunday is reserved for the wife. But @mcelearr can see FAC from his balcony, maybe we could have a chat there before the meetup on Monday?

**Comment by mcelearr** [comment]
@shouston3 Wanna go grab some lunch today? I live right next to FAC so any time suits me.

**Comment by samhstn** [comment]
@coudrew @mcelearr What decision have we come to about hosting? So we can close this issue
May I suggest just gh-pages while it is in the front end, then heroku when we have a server running
Reasons for Heroku:
It's free and easy
I've used it a fair bit and can give you a hand with it
For almost all situations we use Heroku at fac so it would be the best one to get used to using

**Comment by coudrew** [comment]
I'm fine with that, closing.
