### ISSUE TITLE
Cookies needed

### ISSUE THREAD

**Issue by coudrew** [mcelearr/JSskillstracker#20]
We need to be able to generate, and check for, cookies to identify client machines and returning users.

**Comment by samhstn** [comment]
@coudrew This is a great idea, setting cookies to save client data is the way to go

**Comment by samhstn** [comment]
@mcelearr @coudrew 
How we are going to set up the cookie:

When the page loads, we check for a cookie.
If there isn't one, we set a default cookie:
cookie: 'numbers=0;strings=0;booleans=0;arrays=0' ...etc

When a datatype is completed, we alter the cookie to reflect this
eg. completing 'strings' alters the cookie to:
cookie: 'numbers=0;strings=1;booleans=0;arrays=0' ...etc

This should happen independently of the 'wheel'. Once this functionality is achieved through checking if the cookie is working correctly (in the chrome dev tools or logging the cookie), then we can hook up the 'wheel' to read the state of the cookie

**Comment by coudrew** [comment]
that sounds pretty good, which page would we want it checking from, index or the radar chart?

**Comment by samhstn** [comment]
@coudrew I think we only have the one index page at the moment, so that page

**Comment by samhstn** [comment]
Cookies are being set from clicking on the completed buttons
The radar now reads the cookies to set up the wheel
Fixed by commit #41
