### ISSUE TITLE
"Welcome" needed

### ISSUE THREAD

**Issue by coudrew** [mcelearr/JSskillstracker#21]
currently the index.html is a login for github (which could use some prettying up itself) we need a welcome screen with links to login, or just browse.

**Comment by samhstn** [comment]
@coudrew I like the idea of that as being the landing page, what is the difference in user experience between logging in and just browsing?

**Comment by mcelearr** [comment]
@shouston3 Someone browsing can see all the content but they have to be logged in to save their progress and come back to it. The ideal would be to allow 'browsers' to convert to users at any point during their session by signing in through github.

**Comment by samhstn** [comment]
No longer relevant, we are aiming for a one page app which will be the welcome page.
Maybe we can change the app to implement this later
