### ISSUE TITLE
Organise file structure

### ISSUE THREAD

**Issue by samhstn** [mcelearr/JSskillstracker#22]
The index.html page is looking amazing guys! I would say you should add some more folders to group what files do what. Eg. frontend, backend, submitNewSkillsContent, ...

**Comment by coudrew** [comment]
looking into this now, going to leave server_b.js in the root folder though, as I'm pretty sure it has to be there on the actual server to work properly.

**Comment by coudrew** [comment]
would it be better to create a new branch for this? I'm assuming so, and that's how I'll proceed, but just so I know for certain next time.

**Comment by coudrew** [comment]
ok, leaving index.html and favicon in the root dir. as well as server_b. moved the rest of the frontend to app/frontend, left the authorization stuff in app/authorize, and when we get some kind of db going I'm assuming app/db will come into play.

**Comment by samhstn** [comment]
You can have the server anywhere you like, how are you currently running the server?
Are you running `node server_b.js`

**Comment by samhstn** [comment]
Great job on the folder restructuring, @mcelearr can close this issue when the pr is merged

**Comment by coudrew** [comment]
to run the server there's a whole command line thing `sudo node --harmony_array_includes server_b.js port=80 client_id=our-client-id client_secret=our-client-secret host=whatver-domain-it's-hooked-up-to` I put a lot of info into command line args to avoid having the client id/secret exposed on github if we went with heroku (they don't give you the option to edit files on a dyno)

**Comment by samhstn** [comment]
@coudrew Oh nice, I've heard harmony is great to use, never used it myself, but it's what founderandcoders.com site uses, so it must be good

You should probably not use sudo command too regularly and besides there are ways to get around it, maybe try the command without sudo

There are ways to not have your environment variables in the command, but this is good for now

Great work btw, I'm really impressed by what you've done with node so far

Part of me is unsure if you are covering too much node too fast and maybe I shouldn't assign you this in case you burn out, but if you are keen to learn more, I would recommend using npm and setting up a package.json file. Learning this will lead on to how to store these environment variables and not have them in the command

**Comment by samhstn** [comment]
The file structure looks good for now, still repeated code though
