### ISSUE TITLE
.md files and length of files

### ISSUE THREAD

**Issue by samhstn** [mcelearr/JSskillstracker#23]
I don't think that you should have two .md files
I think there is may be a need for concern that the index page is getting a bit long, anything over 100 lines generally isn't good. 
Also, there is a fair bit of repeated code (this can make your files hard to read).
From the index you should take out any javascript in script tags and put it into a separate javascript file.
Consider generating the lorem ipsum list with javascript so it isn't reapeated so many times
Lines 52 to 60 is kind of a repeat of 72
Lastly, what is the difference between the index.html file and the app/radar.html file, maybe look into shortening or removing parts of this
The javascript on line 304 could perhaps be shortened and made more readable

**Comment by coudrew** [comment]
I think the index/radar duplicate happened during conflict resolution for merging the webapp branch to master. the index should have been a login screen, though really that should be it's own page, with the index as the "welcome to some awesome app" page. I'll see if I can get the login page (which still needs some prettying up) back in without creating any conflicts.

**Comment by mcelearr** [comment]
I am going to work on tidying up the index file now.

**Comment by samhstn** [comment]
Closing this as the files are a lot tidier, the index page could still be refactored to remove the repeated code from lines 34 to 106 in the index.html, but all else looks good
