### ISSUE TITLE
Overall look

### ISSUE THREAD

**Issue by coudrew** [mcelearr/JSskillstracker#25]
We need to come up with an overall look and feel for this. Color palettes, page layouts, that kind of thing.

**Comment by mcelearr** [comment]
Actually, just on this. The front-end workshop yesterday was on materialize. It's a front-end framework similar to bootstrap but maybe a little bit better IMO and I think it would be more suitable than what we have at the moment so I'm going to see if we can switch over frameworks.

**Comment by samhstn** [comment]
Looking slick thanks @mcelearr . I think ill close this, the overall look doesn't need work atm imo

**Comment by coudrew** [comment]
so good
