### ISSUE TITLE
Design the interface

### ISSUE THREAD

**Issue by mcelearr** [mcelearr/JSskillstracker#4]
It would be easy to track all these things on a spreadsheet. The challenge here is coming up with a cool interface that will show progress graphically.

We need to do some research into libraries that can turn data from database format to some kind of cool interface.

**Comment by coudrew** [comment]
just an idea, but [phaser js](http://phaser.io/) or it's renderer [pixi.js](http://www.pixijs.com/) might be coerced into taking data from a database (with a clever thing)

**Comment by mcelearr** [comment]
Here are a few of the chart things I found:

http://www.visualcinnamon.com/2015/10/different-look-d3-radar-chart.html
http://www.chartjs.org/docs/#radar-chart

**Comment by coudrew** [comment]
i like the first one, i like the radar chart in general, but the one with the curves is much nicer looking

**Comment by mcelearr** [comment]
I think we've got an outline interface now so I'm going to shut this one down. I'm sure there will be lots more improvements to make to the interface but they can go on as individual issues.
