### ISSUE TITLE
Be able to remove a completed skill

### ISSUE THREAD

**Issue by samhstn** [mcelearr/JSskillstracker#42]
When you click 'completed' the radar responds correctly, but when you click it again it doesn't revert back to uncompleted.
It would be a nice functionality to have.
Also, I think we had that functionality before

**Comment by coudrew** [comment]
I can implement that functionality pretty easily, but I didn't see how it would be useful (outside of accidentally clicking completed I suppose).

**Comment by samhstn** [comment]
Fair point, maybe @mcelearr should decide if this should be changed or left as it is, I'm easy either way

**Comment by mcelearr** [comment]
yes it should be able to change back so people can go back if they make a mistake. Also if they just want to have a play!

**Comment by samhstn** [comment]
Fixed by #45 , good work @coudrew
