### ISSUE TITLE
The completed toggle should reflect if it has been clicked or not

### ISSUE THREAD

**Issue by samhstn** [mcelearr/JSskillstracker#43]
If it hasn't been completed it should display 'incomplete', when you click it, it should display 'completed'
Maybe adding a color change when this happens would be good

**Comment by mcelearr** [comment]
Yeah I agree. Also, it would be good if the more info and incomplete/buttons were different colours.

**Comment by mcelearr** [comment]
I can do this tonight/ tomorrow.

**Comment by samhstn** [comment]
@mcelearr how did you get on with this? Do you need any help?

**Comment by mcelearr** [comment]
Hi @shouston3 I started a branch called buttons. Got them to change colour, just need it to change the inner HTML and icon. I'll have another go and shout for help if I'm struggling.

**Comment by mcelearr** [comment]
Completed by #48
