### ISSUE TITLE
Design database

### ISSUE THREAD

**Issue by mcelearr** [mcelearr/JSskillstracker#5]
How will we track the users and what skills they have done?

**Comment by samhstn** [comment]
@mcelearr How is this one coming along? Do you mean when they complete a skill, that information being stored? I think a cookie or local storage may be best rather than a database

**Comment by coudrew** [comment]
@shouston3 we haven't gotten much further than acknowledging the need to store data _somewhere_. My only concern with a cookie would be lost progress if the cookie expires or is erased. I don't personally know a lot about data storage in this context though, so my ideas are limited to SQL or a JSON array.

**Comment by mcelearr** [comment]
@shouston3 I had in my mind that users can go away, change computers and can come back to their session later. There's also a phase two that's also in the back of my mind when you can compare your progress to your friends (the radar chart can overlay the second data set in a different colour - it looks pretty cool). I thought the only way to do that would be through a database which stores where different users are so that's why we were leaning that way. But as @coudrew says we basically have nothing done on this so far so open to suggestions!

**Comment by samhstn** [comment]
You are right that the only way to do what you said is to use a database and have the users log in, but as you say this could be implemented in the second phase of your app.
As it may take a while to implement a log in and database I think that (at least initially) you should set a cookie.
Setting a cookie is relatively easy and would achieve a similar functionality.

**Comment by coudrew** [comment]
yeah it's just `"Set-Cookie" : "aCookie"` in the response headers right?

**Comment by samhstn** [comment]
Its easier than that. Check out the [w3 cookies](http://www.w3schools.com/js/js_cookies.asp) explanation of how to set and use them

**Comment by samhstn** [comment]
Issue #20 is more relevant now as we should set cookies instead
