### ISSUE TITLE
Create global list of skills

### ISSUE THREAD

**Issue by mcelearr** [mcelearr/JSskillstracker#53]
List of skills and subskills should be unified and stored in one place. Cookie and any dynamically created content should all refer to this unified list.

Create a 2D array (this may be slower due to double loop) in database.js to hold the skills and subskills.

Make sure JS files are being loaded in the correct order. e.g. load the div ids before dynamically creating the content.

**Comment by coudrew** [comment]
Solved by [#55](https://github.com/mcelearr/JSskillstracker/pull/55)
