### ISSUE TITLE
Complete dummy user profiles

### ISSUE THREAD

**Issue by mcelearr** [mcelearr/JSskillstracker#57]
It would be cool if they could be labelled so people could see who each one belongs to.

**Comment by mcelearr** [comment]
I've completed my one. Once #61 has been merged, @coudrew add your own skills into rows 61-76 in skillstracker.js

**Comment by coudrew** [comment]
solved by [#61](https://github.com/mcelearr/JSskillstracker/pull/61) and enhanced by [#63](https://github.com/mcelearr/JSskillstracker/pull/61)
